apiVersion: v1
kind: Service
metadata:
  name: bible-service
  namespace: bible-system

spec:
  type: ClusterIP

  ports:
  - name: bible
    port: 3000
    targetPort: bible
  - name: bible-debug
    port: 3010
    targetPort: bible-debug
  - name: metrics
    port: 4000
    targetPort: metrics
  - name: metrics-debug
    port: 4010
    targetPort: metrics-debug
  - name: prometheus
    port: 4020
    targetPort: metrics-prom
