site_name: KJVonly
theme:
  name: readthedocs
  color_mode: dark
  user_color_mode_toggle: true
  highlightjs: true
  hljs_languages:
    - typescript
    - svelte
    - css
markdown_extensions:
  - admonition